let products=[],cart=[],store={categories:[],settings:{},deliveryZones:[],deliveryKmRanges:[]};
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
async function loadStore(){try{const r=await fetch('/api/store',{cache:'no-store'});if(!r.ok)throw Error();store=await r.json();products=store.products||[];renderCategories();renderProducts();setupDelivery();}catch(e){document.querySelector('#products').innerHTML='<p class="error">Inicie o servidor pelo INICIAR.bat.</p>';}}
function renderCategories(){const cats=store.categories?.length?store.categories:[...new Set(products.map(p=>p.cat).filter(Boolean))];document.querySelector('#categories').innerHTML=cats.map(c=>`<a class="cat" href="#cat-${slug(c)}">${esc(c)}</a>`).join('');}
function slug(s){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');}
function renderProducts(){const cats=store.categories?.length?store.categories:[...new Set(products.map(p=>p.cat).filter(Boolean))];document.querySelector('#products').innerHTML=cats.map(cat=>{const list=products.filter(p=>p.cat===cat);if(!list.length)return '';return `<section class="category-section" id="cat-${slug(cat)}"><div class="category-title"><span class="eyebrow">CARDÁPIO</span><h3>${esc(cat)}</h3><span class="category-line"></span></div><div class="products">${list.map(productCard).join('')}</div></section>`}).join('')||'<p class="error">Nenhum produto disponível.</p>';}
function foodIcon(cat=''){const c=normalizeText(cat);if(c.includes('pizza'))return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M8 10c18 3 34 13 48 30L44 55 8 10Z" fill="none" stroke="currentColor" stroke-width="3"/><circle cx="27" cy="25" r="4" fill="currentColor"/><circle cx="38" cy="34" r="4" fill="currentColor"/></svg>';if(c.includes('bebida'))return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M19 9h26l-3 47H22L19 9Z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M20 18h25" stroke="currentColor" stroke-width="3"/><path d="M39 9c2-5 7-6 8-3" fill="none" stroke="currentColor" stroke-width="3"/></svg>';if(c.includes('aça')||c.includes('acai'))return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M18 12h28l-3 44H21l-3-44Z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M18 21h28M23 29h18" stroke="currentColor" stroke-width="3"/></svg>';if(c.includes('combo'))return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M12 25h40v27H12z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M18 25V14h28v11M20 38h24" fill="none" stroke="currentColor" stroke-width="3"/></svg>';return '<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M10 27h44l-4 18H14l-4-18Z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M14 21c6-9 30-9 36 0M15 33h34M20 45h24" fill="none" stroke="currentColor" stroke-width="3"/></svg>';}
function productCard(p){return `<article class="product"><div class="food-img">${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}">`:`<div class="food-placeholder">${foodIcon(p.cat)}</div>`}<span class="ember-dot"></span></div><div class="product-body"><span class="product-cat">${esc(p.cat||'Especial')}</span><h3>${esc(p.name)}</h3><p>${esc(p.desc||'')}</p><div class="price-row"><span class="price">${money(p.price)}</span><button class="add" onclick="add(${p.id})">+ Adicionar</button></div></div></article>`;}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({...p,qty:1});renderCart();openCart();}
function change(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);renderCart();}
function renderCart(){document.querySelector('#cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0);document.querySelector('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-item"><div class="cart-item-top"><strong>${i.qty}x ${esc(i.name)}</strong><span>${money(i.price*i.qty)}</span></div><div class="qty"><button onclick="change(${i.id},-1)">−</button><span>${i.qty}</span><button onclick="change(${i.id},1)">+</button></div></div>`).join(''):'<p class="empty">Seu carrinho está vazio.</p>';document.querySelector('#subtotal').textContent=money(cart.reduce((s,i)=>s+i.price*i.qty,0));}
function openCart(){document.querySelector('#cart').classList.add('open');document.querySelector('#overlay').classList.add('show')}function closeCart(){document.querySelector('#cart').classList.remove('open');document.querySelector('#overlay').classList.remove('show')}
document.querySelector('#cartBtn').onclick=openCart;document.querySelector('#clearCart').onclick=()=>{cart=[];renderCart();closeCart();};document.querySelector('#closeCart').onclick=closeCart;document.querySelector('#overlay').onclick=closeCart;document.querySelector('#checkoutBtn').onclick=()=>{if(!cart.length)return alert('Adicione pelo menos um produto.');document.querySelector('#checkoutModal').classList.add('show');closeCart()};document.querySelector('#closeModal').onclick=()=>document.querySelector('#checkoutModal').classList.remove('show');
let deliveryZones=[];const normalizeText=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();function findDeliveryZone(neighborhood,street){const nb=normalizeText(neighborhood),st=normalizeText(street);if(!nb)return null;const same=deliveryZones.filter(z=>z.active!==false&&normalizeText(z.neighborhood)===nb);if(!same.length)return null;const exact=same.find(z=>st&&normalizeText(z.street)===st);return exact||same.find(z=>!normalizeText(z.street))||null;}
function setupDelivery(){deliveryZones=store.deliveryZones||[];const type=document.querySelector('#deliveryType'),bairro=document.querySelector('#neighborhood'),rua=document.querySelector('#street'),fee=document.querySelector('#deliveryFee'),feePreview=document.querySelector('#deliveryFeePreview'),fields=document.querySelector('#deliveryFields'),addr=document.querySelector('#address'),addrLabel=document.querySelector('#addressLabel'),hint=document.querySelector('#deliveryHint'),nbList=document.querySelector('#neighborhoodList'),streetList=document.querySelector('#streetList');if(!type||!bairro)return;nbList.innerHTML=[...new Set(deliveryZones.map(z=>z.neighborhood).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(x=>`<option value="${esc(x)}">`).join('');function refreshStreetSuggestions(){const nb=normalizeText(bairro.value);streetList.innerHTML=[...new Set(deliveryZones.filter(z=>z.active!==false&&normalizeText(z.neighborhood)===nb&&normalizeText(z.street)).map(z=>z.street))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(x=>`<option value="${esc(x)}">`).join('');}function buildAddress(){if(type.value==='Retirada'){addr.value='Retirada na loja';return;}const street=rua.value.trim(),num=document.querySelector('[name=number]').value.trim(),comp=document.querySelector('[name=complement]').value.trim(),ref=(document.querySelector('[name=reference]')?.value||'').trim();addr.value=[street,num&&('Nº '+num),bairro.value.trim(),comp,ref&&('Referência: '+ref)].filter(Boolean).join(', ');}function update(){const retirada=type.value==='Retirada';fields.style.display=retirada?'none':'block';addrLabel.style.display=retirada?'none':'block';addr.required=!retirada;bairro.required=!retirada;rua.required=!retirada;document.querySelector('[name=number]').required=!retirada;if(retirada){fee.value='0';feePreview.textContent=money(0);hint.textContent='Retirada na loja: sem taxa de entrega.';addr.value='Retirada na loja';return;}refreshStreetSuggestions();const zone=findDeliveryZone(bairro.value,rua.value);if(zone){const v=Number(zone.fee)||0;fee.value=String(v);feePreview.textContent=money(v);hint.textContent=normalizeText(zone.street)?`Taxa aplicada para ${zone.street}.`:`Taxa fixa do bairro ${zone.neighborhood}.`;}else{fee.value='0';feePreview.textContent='Não cadastrada';hint.textContent='A taxa aparece automaticamente quando o bairro/rua estiver cadastrado pela loja.';}buildAddress();}type.onchange=update;bairro.oninput=update;bairro.onchange=update;rua.oninput=update;rua.onchange=update;document.querySelector('[name=number]').oninput=buildAddress;document.querySelector('[name=complement]').oninput=buildAddress;update();}
document.querySelector('#orderForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return;const f=new FormData(e.target),formData=Object.fromEntries(f),subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0);if(formData.delivery!=='Retirada'&&store.settings?.deliveryMode!=='km'&&!findDeliveryZone(formData.neighborhood,formData.street)){alert('Essa região ainda não possui taxa de entrega cadastrada pela loja. Confira o bairro e a rua.');return;}if(formData.delivery!=='Retirada'&&store.settings?.deliveryMode==='km'&&(!formData.lat||!formData.lng)){try{const q=await quoteAddressDelivery(formData);formData.lat=q.lat;formData.lng=q.lng;formData.deliveryFee=q.deliveryFee;document.querySelector('#customerLat').value=q.lat;document.querySelector('#customerLng').value=q.lng;document.querySelector('#deliveryFee').value=q.deliveryFee;}catch(err){alert(err.message||'Confira o endereço e calcule a entrega.');return;}}const order={customer:formData,items:cart.map(({id,name,price,qty})=>({id,name,price,qty})),subtotal,deliveryFee:formData.delivery==='Retirada'?0:Number(formData.deliveryFee||0),total:subtotal+(formData.delivery==='Retirada'?0:Number(formData.deliveryFee||0))};try{const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(order)});const saved=await r.json();if(!r.ok)throw Error(saved.error||'Erro');const itens=saved.items.map(i=>`${i.qty}x ${i.name} — ${money(i.price*i.qty)}`).join('\n');const msg=`NOVO PEDIDO ${String(saved.number).padStart(2,'0')}\n\nCliente: ${saved.customer.name}\nWhatsApp: ${saved.customer.phone}\n\nPEDIDO:\n${itens}\n\nSUBTOTAL: ${money(saved.subtotal)}\nENTREGA: ${money(saved.deliveryFee)}\nTOTAL: ${money(saved.total)}\n\nENDEREÇO:\n${saved.customer.address}\n\nPAGAMENTO: ${saved.customer.payment}\n\nOBSERVAÇÃO:\n${saved.customer.note||'Nenhuma'}`;const popup=window.open('about:blank','_blank');if(popup)popup.location='https://wa.me/'+store.settings.whatsapp+'?text='+encodeURIComponent(msg);cart=[];renderCart();document.querySelector('#checkoutModal').classList.remove('show');e.target.reset();setupDelivery();document.querySelector('#successTitle').textContent=`Pedido ${String(saved.number).padStart(2,'0')} confirmado!`;document.querySelector('#successText').textContent='Recebemos seu pedido. Os detalhes foram encaminhados para o WhatsApp da loja.';document.querySelector('#successModal').classList.add('show');}catch(err){alert(err.message||'Não foi possível enviar o pedido.');}};
loadStore();renderCart();setInterval(loadStore,15000);

function updatePixCheckout(){const pay=document.querySelector('[name="payment"]')?.value;const b=document.querySelector('#pixCheckout');if(!b)return;const show=pay==='Pix'&&store?.settings?.pixKey;b.style.display=show?'flex':'none';if(show){document.querySelector('#pixCheckoutKey').textContent=store.settings.pixKey;document.querySelector('#pixCheckoutRecipient').textContent=(store.settings.pixRecipient||'')+(store.settings.pixType?' · '+store.settings.pixType:'');const im=document.querySelector('#pixCheckoutQr');if(store.settings.pixQr){im.src=store.settings.pixQr;im.style.display='block'}else im.style.display='none'}}
document.querySelector('[name="payment"]')?.addEventListener('change',updatePixCheckout);document.querySelector('#checkoutBtn')?.addEventListener('click',()=>setTimeout(updatePixCheckout,0));document.querySelector('#copyPixBtn')?.addEventListener('click',async()=>{const k=store?.settings?.pixKey||'';if(!k)return;try{await navigator.clipboard.writeText(k)}catch{const t=document.createElement('textarea');t.value=k;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}alert('Chave PIX copiada!')});
let lastOrderForReceipt=null;const originalSubmit=document.querySelector('#orderForm').onsubmit;document.querySelector('#orderForm').onsubmit=async function(e){await originalSubmit.call(this,e);};
const receiptBtn=document.querySelector('#sendReceiptBtn');if(receiptBtn)receiptBtn.onclick=()=>{const n=(store?.settings?.botWhatsapp||store?.settings?.whatsapp||'').replace(/\D/g,'');if(n)window.open('https://wa.me/'+n+'?text='+encodeURIComponent('Olá! Já fiz o pagamento PIX e vou enviar o comprovante do meu pedido.'),'_blank')};
new MutationObserver(()=>{const sm=document.querySelector('#successModal');if(receiptBtn&&sm?.classList.contains('show'))receiptBtn.style.display=(document.querySelector('[name="payment"]')?.value==='Pix')?'block':'none'}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});

// V5 ponto de referência: mantém endereço atualizado
setTimeout(()=>{const r=document.querySelector('[name=reference]');if(r)r.addEventListener('input',()=>document.querySelector('[name=number]')?.dispatchEvent(new Event('input')))},0);

async function quoteRoadDelivery(lat,lng){const r=await fetch('/api/delivery-quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lat,lng})});const j=await r.json();if(!r.ok)throw Error(j.error||'Não foi possível calcular a rota.');return j}
document.querySelector('#useLocation')?.addEventListener('click',()=>{const st=document.querySelector('#gpsStatus');if(!navigator.geolocation){st.textContent='GPS não disponível neste aparelho.';return}st.textContent='Obtendo localização e calculando rota pelas ruas...';navigator.geolocation.getCurrentPosition(async pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;document.querySelector('#customerLat').value=lat;document.querySelector('#customerLng').value=lng;if(store.settings?.deliveryMode==='km'){try{const x=await quoteRoadDelivery(lat,lng);document.querySelector('#deliveryFee').value=x.deliveryFee;document.querySelector('#deliveryFeePreview').textContent=money(x.deliveryFee);st.textContent=`Rota calculada • ${Number(x.distanceKm).toFixed(1)} km • taxa ${money(x.deliveryFee)}`+(x.routeType==='fallback'?' • estimativa temporária':'');}catch(e){document.querySelector('#deliveryFee').value='0';document.querySelector('#deliveryFeePreview').textContent='Fora da área';st.textContent=e.message}}else st.textContent='Localização registrada. A taxa atual é calculada pelo bairro/rua.'},()=>{st.textContent='Não foi possível acessar a localização. Permita o GPS no navegador.'},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})});


// V9.2 — CEP + endereço editável + geocodificação e rota real
async function lookupCepValue(cep){
  const clean=String(cep||'').replace(/\D/g,'');
  if(clean.length!==8) throw Error('Digite um CEP com 8 números.');
  const r=await fetch('/api/cep/'+clean); const j=await r.json();
  if(!r.ok) throw Error(j.error||'CEP não encontrado.'); return j;
}
async function quoteAddressDelivery(data){
  const payload={cep:data.cep||document.querySelector('#cep')?.value||'',street:data.street||document.querySelector('#street')?.value||'',number:data.number||document.querySelector('[name=number]')?.value||'',neighborhood:data.neighborhood||document.querySelector('#neighborhood')?.value||''};
  const r=await fetch('/api/delivery-quote-address',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const j=await r.json();
  if(!r.ok) throw Error(j.error||'Não foi possível localizar esse endereço.'); return j;
}
function formatCepInput(el){let v=el.value.replace(/\D/g,'').slice(0,8);el.value=v.length>5?v.slice(0,5)+'-'+v.slice(5):v;}
document.querySelector('#cep')?.addEventListener('input',e=>formatCepInput(e.target));
document.querySelector('#lookupCep')?.addEventListener('click',async()=>{
  const st=document.querySelector('#cepStatus'), cep=document.querySelector('#cep'); st.textContent='Buscando CEP...';
  try{const x=await lookupCepValue(cep.value); if(x.street)document.querySelector('#street').value=x.street;if(x.neighborhood)document.querySelector('#neighborhood').value=x.neighborhood;st.textContent='CEP encontrado. Confira rua, bairro e informe o número.';document.querySelector('[name=number]')?.focus();document.querySelector('#street').dispatchEvent(new Event('input',{bubbles:true}));}
  catch(e){st.textContent=e.message}
});
async function calculateByTypedAddress(){
  const st=document.querySelector('#gpsStatus'); st.textContent='Localizando endereço e calculando rota...';
  try{const x=await quoteAddressDelivery({});document.querySelector('#customerLat').value=x.lat;document.querySelector('#customerLng').value=x.lng;document.querySelector('#deliveryFee').value=x.deliveryFee;document.querySelector('#deliveryFeePreview').textContent=money(x.deliveryFee);st.textContent=`Endereço localizado • rota ${Number(x.distanceKm).toFixed(1)} km • taxa ${money(x.deliveryFee)}`;return x;}catch(e){document.querySelector('#deliveryFee').value='0';document.querySelector('#deliveryFeePreview').textContent='Confira o endereço';st.textContent=e.message;throw e;}
}
['#street','#neighborhood','[name=number]','#cep'].forEach(sel=>document.querySelector(sel)?.addEventListener('change',()=>{document.querySelector('#customerLat').value='';document.querySelector('#customerLng').value='';}));
const oldLocationButton=document.querySelector('#useLocation');
if(oldLocationButton){const typed=document.createElement('button');typed.type='button';typed.className='secondary full';typed.id='calculateAddressRoute';typed.textContent='🗺️ CALCULAR ENTREGA PELO ENDEREÇO';oldLocationButton.parentNode.insertBefore(typed,oldLocationButton);typed.addEventListener('click',calculateByTypedAddress);}
