let API_BASE = window.CHEFE_API_BASE || (location.protocol==='file:' ? '' : location.origin);
let token=localStorage.getItem('chefeAdminToken')||'',state={};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
async function discoverBase(){for(const p of [3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010]){try{const r=await fetch('http://127.0.0.1:'+p+'/api/health',{cache:'no-store'});if(r.ok){const h=await r.json();if(h.ok&&h.store==='CHEFE TELLES'&&h.version==='2.0.0'){API_BASE='http://127.0.0.1:'+p;localStorage.setItem('chefeApiBase',API_BASE);return API_BASE}}}catch(e){}}throw Error('Não foi possível conectar ao servidor. Execute o INICIAR.bat.');}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};try{const r=await fetch(API_BASE+path,opt);let d={};try{d=await r.json()}catch{}if(r.status===401){token='';localStorage.removeItem('chefeAdminToken');showLogin();throw Error('Não autorizado')}if(!r.ok)throw Error(d.error||'Erro no servidor');return d}catch(first){if(location.protocol==='file:' || !API_BASE){API_BASE=await discoverBase();const r=await fetch(API_BASE+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||'Erro no servidor');return d}throw first}}
function showLogin(){$('#login').classList.remove('hidden');$('#app').classList.add('hidden')}function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const d=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('#password').value})});token=d.token;localStorage.setItem('chefeAdminToken',token);$('#password').value='';showApp();await refreshAll()}catch(err){$('#loginError').textContent=err.message}};
$('#viewStore').onclick=e=>{if(location.protocol==='file:'){e.preventDefault();discoverBase().then(base=>window.open(base+'/','_blank')).catch(()=>{})}};$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST'})}catch{}token='';localStorage.removeItem('chefeAdminToken');showLogin()};
function openTab(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='orders')loadOrders();if(id==='products')loadProducts();if(id==='categories')loadCategories();if(id==='delivery')loadZones()}
$$('.nav').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>openTab(b.dataset.go));$('#refresh').onclick=refreshAll;$('#refreshOrders').onclick=loadOrders;
async function refreshAll(){state=await api('/api/admin');renderDashboard();renderSettings();await loadOrders();await loadCategories();await loadProducts();await loadZones();$('#serverAddress').textContent=location.origin+'/'; await loadNetworkLinks();}

async function loadNetworkLinks(){const box=$('#serverLinks');if(!box)return;try{const d=await api('/api/network');const port=location.port||'3000';const ips=d.ips||[];box.innerHTML=ips.length?ips.map(ip=>`<div><span>ACESSO PELO CELULAR</span><b>http://${ip}:${port}/</b><br><small>PAINEL: http://${ip}:${port}/admin</small></div>`).join(''):'<div><span>REDE</span><b>IP não detectado</b></div>';}catch{box.innerHTML='<div><span>REDE</span><b>Execute o servidor pelo INICIAR.bat.</b></div>';}}

function renderDashboard(){const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'}),os=(state.orders||[]).filter(o=>o.day===today);$('#statOrders').textContent=os.length;$('#statRevenue').textContent=money(os.reduce((s,o)=>s+Number(o.total||0),0));$('#statNew').textContent=os.filter(o=>o.status==='Novo').length;$('#statProducts').textContent=(state.products||[]).filter(p=>p.active!==false).length}
async function loadOrders(){try{const os=await api('/api/orders');state.orders=os;renderDashboard();$('#ordersList').innerHTML=os.length?os.map(o=>`<article class="order"><div><h3>NOVO PEDIDO ${String(o.number).padStart(2,'0')}</h3><p><b>${esc(o.customer?.name||'Cliente')}</b> · ${esc(o.customer?.phone||'')}</p><p>${o.customer?.delivery==='Retirada'?'Retirada na loja':'Entrega · '+esc(o.customer?.address||'')}</p><p>${(o.items||[]).map(i=>`${i.qty}x ${esc(i.name)}`).join(' · ')}</p><p class="total">${money(o.total)} <span class="tag">${esc(o.customer?.payment||'')}</span></p></div><div class="order-actions"><select data-status="${o.id}">${['Novo','Em preparo','Pronto','Saiu para entrega','Entregue','Cancelado'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="btn" data-print="${o.id}">Imprimir</button></div></article>`).join(''):'<div class="panel">Nenhum pedido ainda.</div>';$$('[data-status]').forEach(s=>s.onchange=async()=>{await api('/api/orders/'+s.dataset.status,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s.value})});await loadOrders()});$$('[data-print]').forEach(b=>b.onclick=()=>printOrder(b.dataset.print))}catch(err){if(token)$('#ordersList').innerHTML='<div class="panel error">'+esc(err.message)+'</div>'}}
function printOrder(id){const u=location.origin+'/print/'+id,ua=navigator.userAgent.toLowerCase();if(/android/.test(ua))location.href='my.bluetoothprint.scheme://'+u;else if(/iphone|ipad|ipod/.test(ua))location.href='bprint://'+u;else window.open('/thermer-test.html?order='+id,'_blank')}
function fillCategorySelect(selected=''){const sel=$('#pCat');sel.innerHTML=(state.categories||[]).map(c=>`<option ${c===selected?'selected':''}>${esc(c)}</option>`).join('')}
function adminFoodIcon(cat=''){const c=String(cat).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(c.includes('pizza'))return '<span class="admin-icon">◉</span>';if(c.includes('bebida'))return '<span class="admin-icon">▱</span>';if(c.includes('acai'))return '<span class="admin-icon">◍</span>';if(c.includes('combo'))return '<span class="admin-icon">▣</span>';return '<span class="admin-icon">◆</span>';}
async function loadProducts(){state=state.categories?state:await api('/api/admin');fillCategorySelect($('#pCat').value);const ps=state.products||[];$('#productsList').innerHTML=ps.map(p=>`<article><div>${p.image?`<img src="${esc(p.image)}" alt="">`:`<div class="thumb">${adminFoodIcon(p.cat)}</div>`}</div><div><h3>${esc(p.name)} <span class="tag">${esc(p.cat)}</span></h3><p>${esc(p.desc||'')}</p><strong>${money(p.price)}</strong></div><div class="actions"><button class="btn" data-edit="${p.id}">Editar</button><button class="btn" data-del="${p.id}">Excluir</button></div></article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));$$('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir este produto do cardápio?')){await api('/api/products/'+b.dataset.del,{method:'DELETE'});await refreshAll()}})}
let imageData='';function resetProduct(){imageData='';$('#productForm').reset();fillCategorySelect((state.categories||[])[0]||'');$('#productId').value='';$('#pPreview').style.display='none';$('#productFormTitle').textContent='Novo produto';$('#productFormPanel').classList.remove('hidden')}
$('#newProduct').onclick=resetProduct;$('#cancelProduct').onclick=()=>$('#productFormPanel').classList.add('hidden');$('#pImage').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>1800000){alert('Use uma imagem de até 1,8 MB.');e.target.value='';return}const rd=new FileReader();rd.onload=()=>{imageData=rd.result;$('#pPreview').src=imageData;$('#pPreview').style.display='block'};rd.readAsDataURL(f)};
async function editProduct(id){const p=(state.products||[]).find(x=>String(x.id)===String(id));if(!p)return;fillCategorySelect(p.cat);$('#productFormPanel').classList.remove('hidden');$('#productFormTitle').textContent='Editar produto';$('#productId').value=p.id;$('#pName').value=p.name;$('#pPrice').value=p.price;$('#pDesc').value=p.desc||'';imageData=p.image||'';if(imageData){$('#pPreview').src=imageData;$('#pPreview').style.display='block'}else $('#pPreview').style.display='none'}
$('#productForm').onsubmit=async e=>{e.preventDefault();const id=$('#productId').value,payload={name:$('#pName').value.trim(),cat:$('#pCat').value,price:Number($('#pPrice').value),desc:$('#pDesc').value.trim(),image:imageData};await api(id?'/api/products/'+id:'/api/products',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#productFormPanel').classList.add('hidden');await refreshAll()};
async function loadCategories(){state=state.categories?state:await api('/api/admin');const cats=state.categories||[];$('#categoriesList').innerHTML=cats.map((c,i)=>`<article class="category-admin-item"><div><strong>${esc(c)}</strong><small>${(state.products||[]).filter(p=>p.cat===c&&p.active!==false).length} produto(s) ativo(s)</small></div><div class="actions"><button class="btn" data-cat-edit="${i}">Editar</button><button class="btn" data-cat-del="${i}">Excluir</button></div></article>`).join('')||'<div class="panel">Nenhuma categoria cadastrada.</div>';$$('[data-cat-edit]').forEach(b=>b.onclick=()=>editCategory(Number(b.dataset.catEdit)));$$('[data-cat-del]').forEach(b=>b.onclick=async()=>{try{await api('/api/categories/'+b.dataset.catDel,{method:'DELETE'});await refreshAll()}catch(e){alert(e.message)}});fillCategorySelect($('#pCat').value)}
function resetCategory(){$('#categoryForm').reset();$('#categoryId').value='';$('#categoryFormPanel').classList.remove('hidden');$('#categoryName').focus()}function editCategory(i){$('#categoryId').value=i;$('#categoryName').value=state.categories[i]||'';$('#categoryFormPanel').classList.remove('hidden');$('#categoryName').focus()}
$('#newCategory').onclick=resetCategory;$('#cancelCategory').onclick=()=>$('#categoryFormPanel').classList.add('hidden');$('#categoryForm').onsubmit=async e=>{e.preventDefault();const id=$('#categoryId').value,name=$('#categoryName').value.trim();await api(id===''?'/api/categories':'/api/categories/'+id,{method:id===''?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});$('#categoryFormPanel').classList.add('hidden');await refreshAll()};
async function loadZones(){state=state.deliveryZones?state:await api('/api/admin');const zs=state.deliveryZones||[];$('#zonesList').innerHTML=zs.length?zs.map(z=>`<article class="zone"><div><h3>${esc(z.neighborhood)}</h3><p>${z.street?`Rua: ${esc(z.street)}`:'Todas as ruas do bairro'}</p><span class="tag">Taxa fixa: ${money(z.fee)}</span></div><div class="actions"><button class="btn" data-zone-edit="${z.id}">Editar</button><button class="btn" data-zone-del="${z.id}">Excluir</button></div></article>`).join(''):'<div class="panel">Nenhuma taxa cadastrada.</div>';$$('[data-zone-edit]').forEach(b=>b.onclick=()=>editZone(b.dataset.zoneEdit));$$('[data-zone-del]').forEach(b=>b.onclick=async()=>{if(confirm('Excluir esta taxa?')){await api('/api/delivery-zones/'+b.dataset.zoneDel,{method:'DELETE'});await refreshAll()}})}
function resetZone(){$('#zoneForm').reset();$('#zoneId').value='';$('#zoneTitle').textContent='Nova taxa';$('#zoneFormPanel').classList.remove('hidden')}$('#newZone').onclick=resetZone;$('#cancelZone').onclick=()=>$('#zoneFormPanel').classList.add('hidden');function editZone(id){const z=(state.deliveryZones||[]).find(x=>String(x.id)===String(id));if(!z)return;$('#zoneFormPanel').classList.remove('hidden');$('#zoneTitle').textContent='Editar taxa';$('#zoneId').value=z.id;$('#zNeighborhood').value=z.neighborhood;$('#zStreet').value=z.street||'';$('#zFee').value=z.fee}
$('#zoneForm').onsubmit=async e=>{e.preventDefault();const id=$('#zoneId').value,payload={neighborhood:$('#zNeighborhood').value.trim(),street:$('#zStreet').value.trim(),fee:Number($('#zFee').value),active:true};await api(id?'/api/delivery-zones/'+id:'/api/delivery-zones',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#zoneFormPanel').classList.add('hidden');await refreshAll()};
function renderSettings(){const s=state.settings||{};$('#sName').value=s.name||'';$('#sWhatsapp').value=s.whatsapp||''}$('#settingsForm').onsubmit=async e=>{e.preventDefault();const payload={name:$('#sName').value.trim(),whatsapp:$('#sWhatsapp').value.trim()};if($('#sPassword').value)payload.adminPassword=$('#sPassword').value;await api('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#sPassword').value='';$('#settingsMsg').textContent='Configurações salvas.';setTimeout(()=>$('#settingsMsg').textContent='',2500)};
if(token){showApp();refreshAll().catch(()=>showLogin())}else showLogin();
